### PR TITLE
First working copy of the back end codebase.

### PR DESCRIPTION
**Pull request by mattecel**
Refactor for 2105 Batch to get backend up and running

### CODE REVIEW

**Review by StillManic — APPROVED** [review]

**Review by sethrknox — APPROVED** [review]
Looks good.

**Review by gregdiaz8624 — APPROVED** [review]

**Comment by SilentMrDave** [comment]
The process we set up was for changes to go into the development branch so they could be tested in the development cluster first before merging them to staging and eventually main. If you'd like to discuss changing this process feel free to send me a message but I'm going to assume this was just accidentally merged directly into main.

**Comment by StillManic** [comment]
It was intended to go to development, I believe the merge to main was a
mistake, sorry about that. We thought that we had merged to development and
that it appeared on main because it had gone through the process. Sorry
about the confusion.

**Comment by SilentMrDave** [comment]
No worries. I'm going to do start a revert so that the dev team can make a new PR for the development branch.

**Pull request merged**
