### PR TITLE
Updating email.properties, aws.properties, and inventoryms/applicatio…

### PR DESCRIPTION
**Pull request by StillManic**
…n.yml to reference environment variables as requested by the devops team.

### CODE REVIEW

**Comment by SilentMrDave** [comment]
Will this PR get approved soon?

**Comment by StillManic** [comment]
Sorry, we got pulled into a meeting, working on that right now.

**Review by JoseJalopeno — APPROVED** [review]

**Review by sethrknox — APPROVED** [review]

**Review by INTONIGHT — APPROVED** [review]
Good to go

**Comment by StillManic** [comment]
@SilentMrDave Merged

**Comment by SilentMrDave** [comment]
Thank you 👍🏾

**Pull request merged**
