### PR TITLE
Feature admin sale

### PR DESCRIPTION
**Pull request by JoseJalopeno**

### CODE REVIEW

**Review by StillManic — APPROVED** [review]

**Comment by StillManic** [comment]
@SilentMrDave Can you guys update the SonarCloud code smells so that they don't complain about "Define a constant instead of duplicating this literal 4 times." in the .sql files?

**Comment by SilentMrDave** [comment]
I got rid of those specific code smells warnings but there are still a lot of others in the inventory service.

**Comment by StillManic** [comment]
Yes, we just pushed a commit fixing them.

**Comment by StillManic** [comment]
Bit annoying that it doesn't like System.out, but whatever.

**Review by mattecel — APPROVED** [review]

**Pull request merged**
