### PR TITLE
Added logging aspect to patch a security vulnerability. Renamed eurek…

### PR DESCRIPTION
**Pull request by StillManic**
…a-server and Spring-Cloud-Gateway to help DevOps team with their pipeline.

### CODE REVIEW

**Comment by StillManic** [comment]
Take note, I'm not sure this commit actually fixes the problem with hyphens, I'm pushing another commit that actually renames the folders.

**Comment by SilentMrDave** [comment]
Ah I missed this comment. The pipeline will fail again while we update it to the new names and get it through a PR.

**Comment by StillManic** [comment]
Should I wait to PR that newer commit that I mentioned until you guys get that PR pulled through?

**Comment by StillManic** [comment]
Oh, wasn't aware it would pull the new commit into this PR.

**Comment by SilentMrDave** [comment]
That's exactly what we wanted so it's fine. We'll get the pipeline updated for you.

**Comment by StillManic** [comment]
Thank you.

**Comment by StillManic** [comment]
Does this PR need to be closed and resubmitted? Or will the checks rerun when they're updated?

**Comment by SilentMrDave** [comment]
They just reran but there's one more commit we need. The pom file in the root directory of the project is still referencing the old names. Once that is updated on your end the pipeline should pass.

**Comment by StillManic** [comment]
That should have updated with commit f53168a.

**Review by SilentMrDave — APPROVED** [review]

**Review by mattecel — APPROVED** [review]

**Pull request merged**
